### ISSUE TITLE
httpx.ConnectError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by ArshCypherZ** [David-Lor/python-qqddm#17]
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions

    yield

  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 62, in start_tls

    raise exc

  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 57, in start_tls

    sock = ssl_context.wrap_socket(

  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket

    return self.sslsocket_class._create(

  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create

    self.do_handshake()

  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake

    self._sslobj.do_handshake()

ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by David-Lor** [comment]
Still working fine over here, are you using a proxy?

**Comment by ArshCypherZ** [comment]
not any that i know of
